### PR TITLE
Add link to Gentoo ebuild for fgallery

### PR DESCRIPTION
**Pull request by robert7k**

### CODE REVIEW

**Comment by wavexx** [comment]
I'm adding some installation instructions to the readme. How do you install this using emerge?

**Comment by robert7k** [comment]
The normal process would be adding the overlay using layman, e.g.
# layman -a robert7k

The ebuild then can be installed using emerge:

# emerge www-apps/fgallery

**Comment by wavexx** [comment]
On Tue, Jan 03 2017, Robert wrote:
> The normal process would be adding the overlay using layman, e.g.
>
> layman -a robert7k
>
> The ebuild then can be installed using emerge:
>
> emerge www-apps/fgallery

I added it.
Could you double-check the readme?

**Comment by robert7k** [comment]
Looks good.

One note: the debian packages are available in testing / unstable only, not in stable. You should mention that in your readme, I think.

**Comment by wavexx** [comment]
On Tue, Jan 03 2017, Robert wrote:
> Looks good.
>
> One note: the debian packages are available in testing / unstable only, not in stable. You should mention that in your readme, I think.

Sadly true :/

**Pull request merged**
