### PR TITLE
sort files to be captioned by filename

### PR DESCRIPTION
**Pull request by TomConlin**
easier to write coherent captions when one leads to the next

### CODE REVIEW

**Comment by wavexx** [comment]
Do you actually feel you need topdown=True to be set? I don't see a big advantage for it.
Also, there's no need to test for "files is not None".

**Comment by TomConlin** [comment]
No need to leave in   ```topdown=True``` Is the default 
I will remove it and push again.

**Comment by wavexx** [comment]
I see no changes in the PR

**Comment by TomConlin** [comment]
it is really pushed now 
https://github.com/wavexx/fgallery/pull/80/commits/3e3b02ea22b6e8fdd40f70905cd2b5da37b72a84

**Comment by wavexx** [comment]
There's still the "files is not None" check. Could you also remove that?
os.walk() returns empty lists if there are no files, so there's no need for this check.

**Pull request merged**
