### PR TITLE
Provide a solution for no-javascript

### PR DESCRIPTION
**Pull request by kensanata**
This involves replacing the h2 in index.html with stuff that's shows the
thumbnails and links to the images, providing alt text and title
attributes based on the first line of the caption. It also uses some CSS
tricks to arrange the thumbnails in columns based on the width of the
display.

Hopefully this will help users linking to their gallery using social
media. At least Google+ seems to pick it up.

If you want to take a look at the result, check out https://alexschroeder.ch/gallery/2016-bretagne/ and look at the source of the index.html file, or disable Javascript in your browser and reload. I didn't investigate why scrolling was disabled, I guess that's some CSS property I ought to override? I ended up scrolling using the arrow keys and liked it. Additional features to consider: the download link to the album.zip – although I don't think it's all that important.

### CODE REVIEW

**Comment by kensanata** [comment]
I guess I could revert the binmode STDOUT if that's what's preventing this request from being merged? Or is there anything else I should look at?

**Comment by wavexx** [comment]
We should have fixed the STDOUT in an earlier issue, right? Hopefully, this shouldn't be necessary anymore.
As for the rest, I just didn't have the time to look at it in depth yet.

One thing I noticed is that you substitute the h2 block in the index file. If you want to do this, you should open the index from the template directory, not the target. Since the gallery can be regenerated in-place, it will fail for the second run.

**Comment by kensanata** [comment]
Replacing the h2 in the template is not what I want. c38a5a11c9c280fddb297f8b113f5e6e54aed4a6 does the right thing: it replaces the entire noscript tag with a new noscript tag, containing the data I want. This works on subsequent runs. Example:
```html
  <body>
    <noscript>
      <div id="photos">
	<a href="imgs/Alex.jpg" title=""><img src="thumbs/Alex.jpg" alt=""/></a>
      </div>
    </noscript>
    <div id="gallery"></div>
  </body>
```

**Comment by kensanata** [comment]
This should now fix #77.

**Comment by kensanata** [comment]
Latest example as generated by the code: https://alexschroeder.ch/gallery/2017-montana/

**Comment by kensanata** [comment]
@wavexx Is there anything I can do to get this pull request merged?

**Comment by wavexx** [comment]
On Thu, Oct 26 2017, Alex Schroeder wrote:
> @wavexx Is there anything I can do to get this pull request merged?

I've been busy on other projects lately, so I didn't have time to review
larger changes.

Sorry about that.

**Pull request closed without merging**
