### PR TITLE
Allow hard/soft/ref - linking to the original image, instead of copy

### PR DESCRIPTION
**Pull request by hamishcoleman**
(Addresses issue #72)

### CODE REVIEW

**Comment by kensanata** [comment]
I like it and merged it into [my copy](https://github.com/kensanata/fgallery). Better than remembering how to run [fdupes](https://en.wikipedia.org/wiki/Fdupes). 👍

**Comment by hamishcoleman** [comment]
@kensanata glad that it was useful for you.   It seems pretty quiet here in upstream...

**Comment by kensanata** [comment]
Yeah, the author pretty much said so in one of me merge requests. I’m starting to think that perhaps we should pick a more active maintainer and follow their fork...

**Comment by wavexx** [comment]
On Sun, Feb 25 2018, Alex Schroeder wrote:
> Yeah, the author pretty much said so in one of me merge requests. I’m
> starting to think that perhaps we should pick a more active maintainer
> and follow their fork...

Please do.

My mind is on other projects right now, and I don't want to hold others
back.

**Comment by ruzickap** [comment]
@kensanata - maybe you should create some PR witch updates the [README.md](https://github.com/wavexx/fgallery/blob/master/README.rst) showing people, where is the active development of `fgallery`.

**Comment by wavexx** [comment]
On Tue, Feb 27 2018, Petr Ruzicka wrote:
> @kensanata - maybe you should create some PR witch updates the README.md showing people,
> where is the active development of fgallery.

If there is some active development going on, I'd recommend changing the
name too. I did the mistake to leave the same name when I took on the
fork of screenkey, and I had endless problems with regular people not
noticing the difference between forks :/

**Comment by kensanata** [comment]
Good point. But what should we use?

**Comment by wavexx** [comment]
On Tue, Feb 27 2018, Alex Schroeder wrote:
> Good point. But what should we use?

I'm more than happy to let you decide :P

**Pull request closed without merging**
