### PR TITLE
This implements some of the most interesting pending pull requests

### PR DESCRIPTION
**Pull request by 0-ast-0**
for https://github.com/wavexx/fgallery which have been integrated
and published at http://pkgsrc.se/wip/fgallery as a pkgsrc "work
in progress" package. In particular the following features are
implemented:
  * Slide show: just click on an image to start, click again to stop
  * Overview mode to see all thumbnails at once
  * A simple no JavaScript mode
  * Perl script fgallery enhancements:
    ** Option -L to use symlinks instead of copies of view library
    ** Option --noblur to skip blurs (and get simply grey noise)
    ** A few Perl improvements
Hopefully these changes will be upstreamed as the pkgsrc patches
have become unwieldy.

### CODE REVIEW

**Comment by kensanata** [comment]
@0-ast-0 Are you still insterested in this? Based on the comment here: https://github.com/wavexx/fgallery/pull/76#issuecomment-368328655 I'm trying to integrate the pull requests that are still out there. If you have any that you want to contribute back, feel free to so so here: https://github.com/kensanata/fgallery

**Comment by 0-ast-0** [comment]
Hello Alex

Yes, I'm interested because I like fgallery and use it for my photo
collections.  I've put the version with all the features I need and
Perl fixups into

http://pkgsrc.se/wip/fgallery

eventually I'll promote it to pkgsrc/www from wip but I make a name
change if the number of diffs remain so high.

Are you "forking" for good? If so, I could take that as the pkgsrc 
src.

Adrian

**Comment by kensanata** [comment]
Yeah, looks like it. In the coming days I will also have to pick a new project name and perhaps that will also mean a new GitHub URL so don't be hasty or you’ll do it all again.

**Comment by kensanata** [comment]
I was unable to download the tgz file?

```
wget http://webgroup.ch/fgallery-1.8.2nb4.tgz
--2018-02-28 23:21:55--  http://webgroup.ch/fgallery-1.8.2nb4.tgz
Resolving webgroup.ch (webgroup.ch)... 2a01:4f8:173:641::4, 188.40.255.45
Connecting to webgroup.ch (webgroup.ch)|2a01:4f8:173:641::4|:80...
connected.
HTTP request sent, awaiting response... No data received.
Retrying.
```

And then it just stays that way.

I downloaded the four patches individually but sadly the first one to
fgallery has many hunks that no longer apply. Can you look into this? The
html and js patch worked no problem, the one failing hunk of the css patch
was easy to add. But the fgallery patch... Ouch!

**Comment by wavexx** [comment]
On Wed, Feb 28 2018, notifications@github.com wrote:
> . wavexx, maybe just maybe, pulling some of my changes but it looks like he's moved on

I'm still using fgallery quite a bit actually ;)
And development was never continuous. fgallery is quite old.

But I don't have time currently for development, and I'd rather not do a
half-assed job. I can always join the fork later!

**Comment by 0-ast-0** [comment]
On Wed, Feb 28, 2018 at 10:24:16PM +0000, Alex Schroeder wrote:
> I was unable to download the tgz file?
> And then it just stays that way.

YEah, I see that now; maybe a IPv6 problem; try 

wget -4 --no-check-certificate http://webgroup.ch/fgallery-1.8.2nb4.tgz


> I downloaded the four patches individually but sadly the first one to
> fgallery has many hunks that no longer apply. Can you look into this? The
> html and js patch worked no problem, the one failing hunk of the css patch
> was easy to add. But the fgallery patch... Ouch!
The pkgsrc version uses diffs agains

http://www.thregr.org/~wavexx/software/fgallery/releases/fgallery-1.8.2.zip

(PORTVERSION=    1.8.2 in pkgsrc Makefile)

Adrian

**Comment by 0-ast-0** [comment]
On Wed, Feb 28, 2018 at 03:01:40PM -0800, wavexx wrote:
> On Wed, Feb 28 2018, notifications@github.com wrote:
> > . wavexx, maybe just maybe, pulling some of my changes but it looks like he's moved on
> 
> I'm still using fgallery quite a bit actually ;)
> And development was never continuous. fgallery is quite old.

Yes, old but good!

> But I don't have time currently for development, and I'd rather not do a
> half-assed job. I can always join the fork later!

Yes I know how that is. So you wouldn't mind if we keep the name and just add some of those features?

I'd probably take what Alex make of it and bump wip/fgallery up and then move it into pkgsrc where more people will "discover" it.

Adrian

**Comment by wavexx** [comment]
On Thu, Mar 01 2018, notifications@github.com wrote:
> Yes I know how that is. So you wouldn't mind if we keep the name and
> just add some of those features?

I don't mind, but I recommend changing the name irregardless.
As a bonus, you can redefine what the "f" means in fgallery ;)

Like I said, my most recent example was taking on the development of
screenkey. Despite the official developer declared the as project dead,
and taking the initiative to fix most bugs and mailing the maintainers
of Arch/Debian/Fedora and most derivatives _and_ several blog posts
citing the fork as the "new" upstream, I still have people asking for
support on the original after more than 3 years. I did the same in the
past taking on mostly-dead projects and I still regretted keeping the
name for the same reason.

**Comment by wavexx** [comment]
On Sat, Mar 03 2018, Yuri D'Elia wrote:
> On Thu, Mar 01 2018, notifications@github.com wrote:
>> Yes I know how that is. So you wouldn't mind if we keep the name and
>> just add some of those features?
>
> I don't mind, but I recommend changing the name irregardless.
> As a bonus, you can redefine what the "f" means in fgallery ;)

One thing that would work better is move the move the project to a new
namespace. Something like fgallery/fgallery.

I could rename it, make you admins, and fork from it again. This would
setup redirects in github correctly. In this case I would also setup
redirects on the main homepage to some other location.

I guess github pages could be used for this as well, but I never used
it. The current homepage is built with my own static generator, so it's
not of much use in this context.

**Comment by kensanata** [comment]
I think we're going to rename the project, soon. Your argument sounds good. Unless I happen to hear good arguments against it, I'm going to rename it to **sitelen-mute**
(see [this issue](https://github.com/kensanata/fgallery/issues/6)). This means the project will eventually reside on `https://github.com/kensanata/sitelen-mute` and `https://github.com/kensanata/fgallery` will end up being an empty repository explaining the move and the renaming.
I was actually hoping to require no other website: everything is part of the repository, or it'll be on my homepage just as the current fgallery stuff is on your homepage. I like self hosting.

**Comment by kensanata** [comment]
Back on the topic of the four patches, @0-ast-0: I find going through `fgallery_patches_patch-fgallery` very labour intensive. Is there some other way? I'm basically trying to figure out which patches you have all integrated, which of these already exist in my copy and which of these are parallel implementations of other patches already integrated. Gaaah. Can you take a look and provide patch that applies cleanly? I'd like to take it. One of the features you will definitely have to check is the noscript solution but the code in your patch looks more readable than what I have.

**Comment by 0-ast-0** [comment]
OK, I just committed something which merges the pkgsrc patches with your
newer version of "fgallery".

See today's master at https://github.com/0-ast-0/fgallery

**Pull request closed without merging**
